FROM node:22.14.0-slim AS builder

RUN corepack enable && corepack prepare pnpm@9.12.3 --activate
WORKDIR /app
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml /app/
COPY apps /app/apps
COPY packages /app/packages
RUN pnpm install --frozen-lockfile
ARG APP
RUN pnpm --filter "@ecoroute/${APP}" build

FROM node:22.14.0-slim AS runner
ARG APP
ENV APP=${APP} \
    NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1
WORKDIR /app
COPY --from=builder /app/apps/${APP}/.next/standalone ./
COPY --from=builder /app/apps/${APP}/.next/static /app/apps/${APP}/.next/static
USER node
CMD ["sh", "-c", "node apps/${APP}/server.js"]
